---
title: "Monte Carlo Applied to Infectious Airborne Diseases"
subtitle: "Stat 400"
author: "Group 1: Robin Thrush and Kaitlynn Walston"
output: 
  ioslides_presentation:
    css: styles.css
---

```{r setup, include=FALSE}
set.seed(445)
knitr::opts_chunk$set(echo = FALSE)
```
## Introduction


## Article

In our article, the researchers attempt to predict the infection rate of an airborne disease when waiting in a waiting room. They did their study on Tuberculous, Measles, and Influenza. They had had specific requirements of room size, ventilation rate, ...

## Assumptions

- Only one infected person in the waiting room
- Once infected, the person can not infect others
- The air being ventilated through the room is mixture of outside air and "infected" air (not being filtered)

## Replication

We had 2 main going into this project:
- we wanted to test their infection rate they found by changing different variables such as room size and how many people were infected
- we wanted to replicate their Monte Carlo approach and apply it to a different disease (SARS)
- quantum - the amount of airborne material required to infect a majority of susceptible individuals exposed to it

## Scenario 1

The room sizer is has an increased size than the one in the article. The exposure time is longer by ____. There is still only one infected person in the room. Before hand, we predicted that the infection probability would decrease. 


## Scenario 2

The room sizer was the same as the one in the article. The exposure time is longer by ____. There is now two infected people in the room. Before hand, we predicted that the infection probability would increase. 


## Scenario 3

The room sizer is has an increased size than the one in the article. The exposure time is shorter by ____.There is now two infected people in the room. Before hand, we predicted that the infection probability would decrease. 



## Results


## New Disease
The disease we wanted to test everything with was SARS. SARS, or severe acute respiratory syndrome, is another common respiratory illness that is typically spread through the air and being is close contact with an infected person. The quanta was: ; the results were: 




## Conclusion

